# Inherit all configuration from the default runtime settings and sets those specific to the distribution
quarkus:
  application:
    name: testapp
  package:
    output-name: keycloak
    output-directory: lib
    type: mutable-jar
    user-providers-directory: ../tmp/providers
    main-class: keycloak
    uber-jar: true
  native:
#    builder-image: quay.io/quarkus/ubi-quarkus-native-image:21.1.1-java17
    builder-image: quay.io/quarkus/ubi-quarkus-native-image
  ssl:
    native: false
#  datasource:
#    db-kind: postgresql
#    jdbc:
#      url: jdbc:postgresql://localhost:5432/kc_db_local
#    username: user01
#    password: passw0rd
#  log:
#    level: DEBUG
#    min-level: DEBUG
#    console:
#      level: DEBUG
