package org.scriptonbasestar.kcext.event.kafka

object KafkaConstant {
    val DEFAULT_GROUP_ID = "default-group-id"
    val DEFAULT_TOPIC = "default-topic"
    val DEFAULT_BOOTSTRAP_SERVERS = "localhost:9092"
    val DEFAULT_AUTO_OFFSET_RESET = "earliest"
    val DEFAULT_KEY_DESERIALIZER = "org.apache.kafka.common.serialization.StringDeserializer"
    val DEFAULT_VALUE_DESERIALIZER = "org.apache.kafka.common.serialization.StringDeserializer"
    val DEFAULT_KEY_SERIALIZER = "org.apache.kafka.common.serialization.StringSerializer"
    val DEFAULT_VALUE_SERIALIZER = "org.apache.kafka.common.serialization.StringSerializer"
    val DEFAULT_ACKS = "1"
    val DEFAULT_RETRIES = "0"
    val DEFAULT_BATCH_SIZE = "16384"
    val DEFAULT_LINGER_MS = "1"
    val DEFAULT_BUFFER_MEMORY = "33554432"
    val DEFAULT_MAX_BLOCK_MS = "60000"
    val DEFAULT_MAX_REQUEST_SIZE = "1048576"
    val DEFAULT_MAX_POLL_RECORDS = "500"
    val DEFAULT_MAX_POLL_INTERVAL_MS = "300000"
    val DEFAULT_SESSION_TIMEOUT_MS = "10000"
    val DEFAULT_HEARTBEAT_INTERVAL_MS = "3000"
    val DEFAULT_METADATA_MAX_AGE_MS = "300000"
    val DEFAULT_AUTO_COMMIT_INTERVAL_MS = "5000"
    val DEFAULT_ENABLE_AUTO_COMMIT = "true"
    val DEFAULT_ISOLATION_LEVEL = "read_committed"
    val DEFAULT_CLIENT_ID = "default-client-id"
    val DEFAULT_CONNECTIONS_MAX_IDLE_MS = "540000"
}
