name: Publish jar

on:
  push:
    tags:
      - '*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
#    if: github-repository == 'scriptonbasestar/sb-keycloak-exts'

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true
